function ants_rigid_registration(movingImageFile, movingMaskFile, fixedImageFile, fixedMaskFile, outputFile)

SamplingRate = '0.25'; % usually 0.25 is enough, increase it for small images

    if (isempty(movingMaskFile)||isempty(fixedMaskFile))
                command = ['cd utils\ANTs_2.1.0_Windows &&',...
            ' antsRegistration.exe',...
            '  --dimensionality 3',...
            '  --float 0',...
            ' --output [',outputFile,',',outputFile,'.nii.gz]',...
            ' --interpolation Linear',...
            ' --winsorize-image-intensities [0.005,0.995]',...
            ' --use-histogram-matching 0',...
            ' --transform Rigid[0.1]',...
            ' --metric MI[',fixedImageFile,',',movingImageFile,',1,32,Regular,',SamplingRate,']',...
            ' --convergence [1000x500x250x100,1e-6,10]',...
            ' --shrink-factors 8x4x2x1',...
            '  --smoothing-sigmas 3x2x1x0vox '];
    else
        command = ['cd utils\ANTs_2.1.0_Windows &&',...
            ' antsRegistration.exe',...
            '  --dimensionality 3',...
            '  --float 0',...
            ' --output [',outputFile,',',outputFile,'.nii.gz]',...
            ' --interpolation Linear',...
            ' --winsorize-image-intensities [0.005,0.995]',...
            ' --use-histogram-matching 0',...
            ' --transform Rigid[0.1]',...
            ' --metric MI[',fixedImageFile,',',movingImageFile,',1,32,Regular,',SamplingRate,']',...
            ' --convergence [1000x500x250x100,1e-6,10]',...
            ' --shrink-factors 8x4x2x1',...
            '  --smoothing-sigmas 3x2x1x0vox ',...
            ' -x [',fixedMaskFile,',',movingMaskFile,']'];
    end
            dos(command,'-echo')
end